### ISSUE TITLE
Streamfield: Image with Text Overlay CSS issue 

### ISSUE THREAD

**Issue by domdinicola** [ibrahimawadhamid/wagtail_blocks#5]
I don't know if it happens only to me but the CSS look in the middle of the image instead of the bottom
- python3.8
- django 3.0.5
- wagtail 2.8.1

**Comment by domdinicola** [comment]
![Screenshot_2020-04-15_19-05-01](https://user-images.githubusercontent.com/2621572/79397410-079a0d80-7f4c-11ea-80cd-08f86528a375.png)

**Comment by ibrahimawadhamid** [comment]
@domdinicola are you still having this issue ?

**Comment by domdinicola** [comment]
yes... I don't think I've conflicts with css

**Comment by kevinjay62** [comment]
I have the same issue.
Adding images changes the css. In my case the menu background color changes and the font is modified.

**Comment by ibrahimawadhamid** [comment]
I'm sorry guys, I don't have enough time to look into this. You are very welcome to fix it and open a pull request.

**Comment by ibrahimawadhamid** [comment]
@tombola Do you have the time to take a look at this as well?

**Comment by tombola** [comment]
@kevinjay62 - I have tested the block type 'Image with Text Overlay' on a blank wagtail site (no other CSS) and I do not see the issue.

I would suggest that this may be a result of other CSS on your site. If you comment out the css where it is included in your base template do you still see that specific issue? Obviously with your site's styling missing it will look a mess, but does the text still sit in the middle of that block?

**Comment by tombola** [comment]
@kevinjay62 re-reading your comment, it looks like you might have had a different issue from @domdinicola, who I am pretty sure has conflicting CSS affecting wagtail-blocks. 

I realise that I am late to the issue, but I will have another look later, in case can resolve for future users of the package. I expect the problem is most likely to arise from the inclusion of boostrap by wagtail-blocks.
